### ISSUE TITLE
Arbeitszeit während Absenz nicht von Absenz abziehen

### ISSUE THREAD

**Issue by nItroFreeZer** [tmtde/SmallTime#1]
Es soll eine Einstellmöglichkeit geben, damit anstelle der Verechnung von Arbeitszeit während der Absenz mit der Absenz, die Arbeitszeit als Plusstunden angerechnet werden.

**Comment by yellowmoneybank** [comment]
Erledigt in: 64c6454944f0d492a12091c9d1741767b1a56b2f
